[package]
name = "input_py"
version = "1.0.0"
edition = "2021"
description = "you can use input like python3"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
